language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: nightly
    allow_failures:
        - php: nightly

before_script:
- composer self-update
- composer dumpautoload
