language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: nightly
        - php: hhvm-nightly
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
    fast_finish: true

before_script:
- composer self-update
- composer dumpautoload
